Pretty print cron conf

diff --git a/bin/cron-apply b/bin/cron-apply
--- a/bin/cron-apply
+++ b/bin/cron-apply
@@ -1,51 +1,67 @@
 #!/bin/bash
 
+set -eu
+
 PROGNAME=$(basename $0)
 FULLPATH=$(dirname $(realpath $0))
 CRON_FILENAME="cron.conf"
 ROOT_CRON_FILENAME="root_cron.conf"
 
-if [ $# -gt 1 ]; then
-  echo "$PROGNAME: Too many arguments" >&2
-  exit 1
-fi
+main() {
+  if [ $# -gt 1 ]; then
+    echo "$PROGNAME: Too many arguments" >&2
+    exit 1
+  fi
 
-if [ -z $1 ]; then
-  echo "$PROGNAME: Missing argument" >&2
-  exit 1
-fi
+  if [ -z $1 ]; then
+    echo "$PROGNAME: Missing argument" >&2
+    exit 1
+  fi
 
-if ! [ -d "$FULLPATH/../$1" ]; then
-  echo "$PROGNAME: No such directory: $FULLPATH/../$1" >&2
-  exit 1
-fi
+  if ! [ -d "$FULLPATH/../$1" ]; then
+    echo "$PROGNAME: No such directory: $FULLPATH/../$1" >&2
+    exit 1
+  fi
 
-if [ "$(whoami)" != "root" ]; then
-  filename=$CRON_FILENAME
-else
-  filename=$ROOT_CRON_FILENAME
-fi
+  if [ "$(whoami)" != "root" ]; then
+    filename=$CRON_FILENAME
+  else
+    filename=$ROOT_CRON_FILENAME
+  fi
 
-if ! [ -e "$FULLPATH/../$1/$filename" ]; then
-  echo "$PROGNAME: No such file: $FULLPATH/../$1/$filename"
-  exit 1
-fi
+  if ! [ -e "$FULLPATH/../$1/$filename" ]; then
+    echo "$PROGNAME: No such file: $FULLPATH/../$1/$filename"
+    exit 1
+  fi
 
-if ! [ -e "$FULLPATH/../$1/private/$filename" ]; then
-  echo "$PROGNAME: No such file: $FULLPATH/../$1/private/$filename"
-  exit 1
-fi
+  if ! [ -e "$FULLPATH/../$1/private/$filename" ]; then
+    echo "$PROGNAME: No such file: $FULLPATH/../$1/private/$filename"
+    exit 1
+  fi
 
-crontab < <(cat "$FULLPATH/../$1/$filename" "$FULLPATH/../$1/private/$filename")
+  crontab < <(print_conf "$@")
 
-if [ "$(diff <(cat "$FULLPATH/../$1/$filename" "$FULLPATH/../$1/private/$filename") <(crontab -l))" != "" ]; then
-  echo "$PROGNAME: It looks like something went wrong" >&2
-  echo >&2
-  echo "The diff shows here:" >&2
-  diff <(cat "$FULLPATH/../$1/$filename" "$FULLPATH/../$1/private/$filename") <(crontab -l) >&2
-  exit 2
-else
-  crontab -l
-fi
+  if [ "$(diff <(print_conf "$@") <(crontab -l))" != "" ]; then
+    echo "$PROGNAME: It looks like something went wrong" >&2
+    echo >&2
+    echo "The diff shows here:" >&2
+    diff <(print_conf "$@") <(crontab -l) >&2
+    exit 2
+  else
+    crontab -l
+  fi
+}
 
-exit 0
+print_conf() {
+  echo "##### BEGIN PUBLIC CRON CONF #####"
+  cat "$FULLPATH/../$1/$filename"
+  echo "##### END PUBLIC CRON CONF #####"
+  echo
+  echo
+  echo
+  echo "##### BEGIN PRIVATE CRON CONF #####"
+  cat "$FULLPATH/../$1/private/$filename"
+  echo "##### END PRIVATE CRON CONF #####"
+}
+
+main "$@"
