Add subcommand to clean-repo

diff --git a/raspberrypi/bin/clean-repo b/raspberrypi/bin/clean-repo
--- a/raspberrypi/bin/clean-repo
+++ b/raspberrypi/bin/clean-repo
@@ -8,6 +8,49 @@ main() {
   parse "$@"
   eval "set -- $REST"
 
+  mode="$1"
+  shift
+
+  case "$mode" in
+    "check")
+      check "$@"
+      ;;
+    "perform")
+      perform "$@"
+      ;;
+    *)
+      echo "error: no such mode: \"$mode\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+check() {
+  result=""
+
+  for TARGET; do
+    if [ "$(git -C "$TARGET" status --porcelain)"             != "" ] ||
+       [ "$(git -C "$TARGET" rev-list HEAD@{upstream}..HEAD)" != "" ]; then
+
+      if [ "$DETAIL" != "1" ]; then
+        echo "1"
+        return
+      fi
+
+      result="${result}1 "
+    else
+      result="${result}0 "
+    fi
+  done
+
+  if [ "$DETAIL" = "1" ]; then
+    echo "$result"
+  else
+    echo "0"
+  fi
+}
+
+perform() {
   for TARGET; do
     # untracked new files
     if [ "$(git -C "$TARGET" status --porcelain | grep "^??")" != "" ]; then
@@ -65,6 +108,7 @@ main() {
 parser_definition() {
   setup   REST help:usage -- "Usage: clean-repo [options]... [arguments]..." ''
   msg -- 'Options:'
+  flag    DETAIL         --detail      -- "show results for each directory"
   flag    IMMEDIATELY    --immediately -- "restart dnsmasq daemon immediately"
   disp    :usage      -h --help        -- "show help message and exit"
   disp    VERSION        --version     -- "show current version and exit"
@@ -74,6 +118,7 @@ parser_definition() {
 # @gengetoptions parser -i parser_definition parse
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
+DETAIL=''
 IMMEDIATELY=''
 REST=''
 parse() {
@@ -89,6 +134,11 @@ parse() {
         OPTARG= ;;
     esac
     case $1 in
+      '--detail')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
+        DETAIL="$OPTARG"
+        ;;
       '--immediately')
         [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
         eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
@@ -130,6 +180,7 @@ cat<<'GETOPTIONSHERE'
 Usage: clean-repo [options]... [arguments]...
 
 Options:
+      --detail                show results for each directory
       --immediately           restart dnsmasq daemon immediately
   -h, --help                  show help message and exit
       --version               show current version and exit
