Add message "From digital-detox-notifier"

diff --git a/raspberrypi/bin/digital-detox-notifier b/raspberrypi/bin/digital-detox-notifier
--- a/raspberrypi/bin/digital-detox-notifier
+++ b/raspberrypi/bin/digital-detox-notifier
@@ -1,9 +1,13 @@
 #!/bin/sh
 
+# to avoid updating COUNT_FILE if gh fails
+set -eu
+
 DAY_SECOND="86400"
 COUNT_FILE="/home/ubuntu/.tmp/digital_detox_notifier_count"
 LOG_FILE="/home/ubuntu/.log/digital_detox_notifier.log"
 REPO="noraworld/diary"
+NEWLINE="\r\n"
 
 main() {
   since=$(systemctl show dnsmasq --property=ActiveEnterTimestamp | sed -r 's/ActiveEnterTimestamp=//g')
@@ -12,9 +16,11 @@ main() {
 
   if { [ "$uptime_days" -gt 0 ] && ! [ -e "$COUNT_FILE" ]; } || { [ "$uptime_days" -gt 0 ] && [ "$uptime_days" -gt "$(cat "$COUNT_FILE")" ]; }; then
     message="You have been on a digital detox for $uptime_days $(pluralize "$@")!"
+    body=$(printf "%s${NEWLINE}${NEWLINE}> From digital-detox-notifier" "$message")
+
     echo "$message ($(date))" >> "$LOG_FILE"
     # TODO: additional compliment message like "keep it up!", "fantastic!", "holy moly!", or whatever
-    gh issue comment --repo "$REPO" "$(gh issue list --repo "$REPO" --limit 1 | awk '{ print $1 }')" --body "$message"
+    gh issue comment --repo "$REPO" "$(gh issue list --repo "$REPO" --limit 1 | awk '{ print $1 }')" --body "$body"
   fi
 
   echo "$uptime_days" > "$COUNT_FILE"
