Confirm before renewing or deleting garnish file
Add option to ignore confirmation

diff --git a/raspberrypi/bin/garnish b/raspberrypi/bin/garnish
--- a/raspberrypi/bin/garnish
+++ b/raspberrypi/bin/garnish
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+# shellcheck disable=SC2004
+
 # https://chat.openai.com/share/a37c2f7c-6ed6-4373-8cfb-5bc2d436e20e
 # https://chat.openai.com/share/77d93a57-a6b4-4c52-a6ad-03726f116ddc
 # https://chat.openai.com/share/8392f873-40ad-4a47-922c-26892a098571
@@ -35,12 +37,28 @@ main() {
 }
 
 prep() {
-  [ -f "$GARLIC_STORAGE" ] && rm -f "$GARLIC_STORAGE"
-  touch "$GARLIC_STORAGE"
+  skipped="false"
 
-  if [ -f "$GARLIC_STORAGE" ]; then
-    echo "$GARLIC_STORAGE created"
+  if [ -f "$GARLIC_STORAGE" ] && [ "$FORCE" != "1" ]; then
+    printf "A piece of garlic has already been prepared. Would you like to prepare it again? [y/N]: "
+    exec < /dev/tty
+    read -r confirm
+
+    if [ "$confirm" = "y" ] || [ "$confirm" = "yes" ]; then
+      rm -f "$GARLIC_STORAGE"
+      touch "$GARLIC_STORAGE"
+    else
+      skipped="true"
+      echo "OK, it won't be created." >&2
+    fi
   else
+    [ -f "$GARLIC_STORAGE" ] && rm -f "$GARLIC_STORAGE"
+    touch "$GARLIC_STORAGE"
+  fi
+
+  if [ -f "$GARLIC_STORAGE" ] && [ "$skipped" = "false" ]; then
+    echo "$GARLIC_STORAGE created"
+  elif ! [ -f "$GARLIC_STORAGE" ] && [ "$skipped" = "false" ]; then
     echo "error: failed to create file $GARLIC_STORAGE for some reason" >&2
   fi
 }
@@ -66,7 +84,31 @@ savor() {
 }
 
 wipe() {
-  [ -f "$GARLIC_STORAGE" ] && rm -f "$GARLIC_STORAGE"
+  skipped="false"
+
+  if ! [ -f "$GARLIC_STORAGE" ]; then
+    echo "A piece of garlic has already been dumped." >&2
+    skipped="true"
+  elif [ -f "$GARLIC_STORAGE" ] && [ "$FORCE" != "1" ]; then
+    printf "Would you like to dump a piece of garlic? [y/N]: "
+    exec < /dev/tty
+    read -r confirm
+
+    if [ "$confirm" = "y" ] || [ "$confirm" = "yes" ]; then
+      rm -f "$GARLIC_STORAGE"
+    else
+      skipped="true"
+      echo "OK, it won't be deleted." >&2
+    fi
+  else
+    rm -f "$GARLIC_STORAGE"
+  fi
+
+  if ! [ -f "$GARLIC_STORAGE" ] && [ "$skipped" = "false" ]; then
+    echo "$GARLIC_STORAGE deleted"
+  elif [ -f "$GARLIC_STORAGE" ] && [ "$skipped" = "false" ]; then
+    echo "error: failed to delete file $GARLIC_STORAGE for some reason" >&2
+  fi
 }
 
 # @getoptions
@@ -78,6 +120,7 @@ parser_definition() {
   msg -- '  wipe                        delete a garnish file'
   msg -- ''
   msg -- 'Options:'
+  flag    FORCE      --force   -- "perform the action without confirmation"
   disp    :usage  -h --help
   disp    VERSION    --version
 }
@@ -86,6 +129,7 @@ parser_definition() {
 # @gengetoptions parser -i parser_definition parse
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
+FORCE=''
 REST=''
 parse() {
   OPTIND=$(($#+1))
@@ -100,6 +144,11 @@ parse() {
         OPTARG= ;;
     esac
     case $1 in
+      '--force')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
+        FORCE="$OPTARG"
+        ;;
       '-h'|'--help')
         usage
         exit 0 ;;
@@ -141,6 +190,7 @@ Argument:
   wipe                        delete a garnish file
 
 Options:
+      --force                 perform the action without confirmation
   -h, --help
       --version
 GETOPTIONSHERE
