Enhance observe-firewall
* Move "punish" to a new file
* Add "deny" and "allow" to "observe-firewall"
* Introduce "punish" to "observe-firewall"
* Use "observe-firewall" differently

diff --git a/raspberrypi/bin/observe-firewall b/raspberrypi/bin/observe-firewall
--- a/raspberrypi/bin/observe-firewall
+++ b/raspberrypi/bin/observe-firewall
@@ -1,7 +1,40 @@
 #!/bin/sh
+# shellcheck disable=SC2004
 
 main() {
-  if ! eval "$(dns_blocked)"; then
+  parse "$@"
+  eval "set -- $REST"
+  authenticate
+
+  operation="$1"
+
+  case "$operation" in
+    "deny")
+      deny "$@"
+      ;;
+    "allow")
+      allow "$@"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+deny() {
+  if ! eval "$(dns_blocked)" || ! eval "$(github_blocked)"; then
+    restore_rules
+    restrict_github
+
+    if [ "$SAFE" != 1 ]; then
+      punish "$@"
+    fi
+  fi
+}
+
+allow() {
+  if eval "$(github_blocked)"; then
     restore_rules
   fi
 }
@@ -13,7 +46,9 @@ restore_rules() {
   # Apply UFW rules
   #   https://github.com/noraworld/ufw-conf
   sudo ufw reload
+}
 
+restrict_github() {
   # Retrieve all IP addresses for GitHub and extract ones used for "git"
   github_git_addresses=$(curl -s https://api.github.com/meta | tr -d '\n' | grep -oP "\"git\": \[(.*?)\]" | sed 's/"git": \[//g' | tr -d ']' | tr -d '"' | tr -d ' ')
 
@@ -51,10 +86,105 @@ dns_blocked() {
     return
   fi
 
+  echo true
+}
+
+github_blocked() {
   # Check if the GitHub IP addresses for "git push" & "git pull" are blocked
-  ssh -T git@github.com > /dev/null 2>&1 && echo false
+  # MEMO: "ssh -T git@github.com" can't be used
+  git -C /home/ubuntu/workspace/cron-conf fetch > /dev/null 2>&1 && echo false && return
 
   echo true
 }
 
-main
+punish() {
+  sh -c "$(dirname "$(realpath "$0")")/../../bin/lib/punish"
+}
+
+authenticate() {
+  IS_CRON_SCRIPT=$(dirname "$(realpath "$0")")/../../bin/lib/is-cron
+
+  if [ "$(sh -c "$IS_CRON_SCRIPT")" = false ]; then
+    echo "Fatal: This operation must be executed by cron, or this script does not take enough effect" >&2
+    exit 2
+  fi
+}
+
+# @getoptions
+parser_definition() {
+  setup   REST help:usage -- "Usage: observe-firewall [options]... [arguments]..." ''
+  msg -- 'Options:'
+  flag    SAFE       --safe    -- "not getting punished"
+  disp    :usage  -h --help    -- "show help message and exit"
+  disp    VERSION    --version -- "show current version"
+}
+# @end
+
+# @gengetoptions parser -i parser_definition parse
+# Generated by getoptions (BEGIN)
+# URL: https://github.com/ko1nksm/getoptions (v3.3.0)
+SAFE=''
+REST=''
+parse() {
+  OPTIND=$(($#+1))
+  while OPTARG= && [ $# -gt 0 ]; do
+    case $1 in
+      --?*=*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
+        ;;
+      --no-*|--without-*) unset OPTARG ;;
+      -[h]?*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
+        OPTARG= ;;
+    esac
+    case $1 in
+      '--safe')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
+        SAFE="$OPTARG"
+        ;;
+      '-h'|'--help')
+        usage
+        exit 0 ;;
+      '--version')
+        echo "${VERSION}"
+        exit 0 ;;
+      --)
+        shift
+        while [ $# -gt 0 ]; do
+          REST="${REST} \"\${$(($OPTIND-$#))}\""
+          shift
+        done
+        break ;;
+      [-]?*) set "unknown" "$1"; break ;;
+      *)
+        REST="${REST} \"\${$(($OPTIND-$#))}\""
+    esac
+    shift
+  done
+  [ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
+  case $1 in
+    unknown) set "Unrecognized option: $2" "$@" ;;
+    noarg) set "Does not allow an argument: $2" "$@" ;;
+    required) set "Requires an argument: $2" "$@" ;;
+    pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
+    notcmd) set "Not a command: $2" "$@" ;;
+    *) set "Validation error ($1): $2" "$@"
+  esac
+  echo "$1" >&2
+  exit 1
+}
+usage() {
+cat<<'GETOPTIONSHERE'
+Usage: observe-firewall [options]... [arguments]...
+
+Options:
+      --safe                  not getting punished
+  -h, --help                  show help message and exit
+      --version               show current version
+GETOPTIONSHERE
+}
+# Generated by getoptions (END)
+# @end
+
+main "$@"
