Add error handling for unknown combination

diff --git a/raspberrypi/bin/observe-dnsmasq-toggle-conf b/raspberrypi/bin/observe-dnsmasq-toggle-conf
--- a/raspberrypi/bin/observe-dnsmasq-toggle-conf
+++ b/raspberrypi/bin/observe-dnsmasq-toggle-conf
@@ -30,6 +30,10 @@ observe() {
             echo "ERROR: The combination of mode \"$MODE\" and event \"$EVENT\" is illegal." >&2
             exit 1
             ;;
+          *)
+            echo "Error: the combination of event $EVENT and mode $MODE is not supported" >&2
+            exit 2
+            ;;
         esac
         ;;
       "delete")
@@ -43,6 +47,10 @@ observe() {
           "cron")
             ca
             ;;
+          *)
+            echo "Error: the combination of event $EVENT and mode $MODE is not supported" >&2
+            exit 2
+            ;;
         esac
         ;;
       "modify")
@@ -53,6 +61,10 @@ observe() {
             ;;
           "cron")
             ca
+            ;;
+          *)
+            echo "Error: the combination of event $EVENT and mode $MODE is not supported" >&2
+            exit 2
             ;;
         esac
         ;;
