Add new restriction "Crimson"
https://the-boys.fandom.com/wiki/Crimson_Countess

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -34,6 +34,9 @@ main() {
     "chime")
       chime
       ;;
+    "crimson")
+      crimson
+      ;;
     "deregulated-superman")
       deregulated_superman
       ;;
@@ -133,6 +136,21 @@ chime() {
       ;;
     "allow")
       remove-dnsmasq-toggle-conf public chime
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+crimson() {
+  case "$operation" in
+    "deny")
+      remove-dnsmasq-toggle-conf private crimson
+      ;;
+    "allow")
+      create-dnsmasq-toggle-conf private crimson
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -45,6 +45,9 @@ main() {
     "chime")
       chime
       ;;
+    "crimson")
+      crimson
+      ;;
     "deregulated-superman")
       deregulated_superman
       ;;
@@ -161,6 +164,28 @@ chime() {
   if [ -L /etc/dnsmasq.toggle/chime.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/chime.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+crimson() {
+  reference_minute=5
+  [ "$DRY_RUN" = 1 ] && exit 0
+  WAITING_INTERVAL=1
+
+  while ! [ -L "/etc/dnsmasq.priv/toggle/crimson.conf" ]; do
+    warning_color
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.priv/toggle/crimson.conf /etc/dnsmasq.priv/toggle
+    no_color
+
+    pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+  done
+
+  if ! [ -L /etc/dnsmasq.toggle/crimson.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/crimson.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
