Introduce Gaming

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -41,6 +41,9 @@ main() {
     "focus")
       focus
       ;;
+    "gaming")
+      gaming
+      ;;
     "github-editor")
       github_editor
       ;;
@@ -227,6 +230,22 @@ focus() {
       # cron-daemonctl stop observe-focus-conf "$safe"
       remove-dnsmasq-toggle-conf private focus
       # remove-iptables-toggle-conf private 232_focus
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+gaming() {
+  case "$operation" in
+    "deny")
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-gaming-conf "$safe"
+      create-dnsmasq-toggle-conf public gaming
+      ;;
+    "allow")
+      cron-daemonctl stop observe-gaming-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -67,6 +67,9 @@ main() {
     "superman")
       superman
       ;;
+    "gaming")
+      gaming
+      ;;
     "vod")
       vod
       ;;
@@ -347,6 +350,25 @@ superman() {
 
   deregulated_superman
   reference_minute=60
+}
+
+gaming() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/gaming.conf
+  no_color
+
+  pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.toggle/gaming.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/gaming.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
 }
 
 vod() {
