Create Discipline as observed file

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -135,6 +135,9 @@ main() {
     "youtube-music-persistent")
       youtube_music_persistent
       ;;
+    "discipline")
+      discipline
+      ;;
     *)
       echo "error: no such service: \"$service\"" >&2
       exit 1
@@ -850,6 +853,29 @@ youtube_music_persistent() {
     "allow")
       :
       cron-daemonctl stop observe-youtube-music-persistent-conf "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+discipline() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$PURPLE_KRYPTONITE" = "1" ] || [ "$RED_KRYPTONITE" = "1" ] || [ "$YELLOW_KRYPTONITE" = "1" ]; then
+        cron-daemonctl stop observe-discipline-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-discipline-conf "$safe"
+      create-dnsmasq-toggle-conf public discipline
+      ;;
+    "allow")
+      cron-daemonctl stop observe-discipline-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -108,6 +108,9 @@ main() {
       "superman-upstream")
         superman_upstream
         ;;
+      "discipline")
+        discipline
+        ;;
       *)
         echo "error: no such service $service" >&2
         exit 1
@@ -242,6 +245,10 @@ all() {
 
   if [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
     sudo unlink /etc/dnsmasq.priv/toggle/superman_upstream.conf
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/discipline.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/discipline.conf
   fi
 
   pause "$waiting_interval" "$WAITING_MESSAGE"
@@ -419,6 +426,14 @@ all() {
   if [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.priv/toggle/superman_upstream.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    # exit
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/discipline.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/discipline.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     # exit
@@ -1115,6 +1130,25 @@ superman_upstream() {
   if ! [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.priv/toggle/superman_upstream.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+discipline() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/discipline.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.toggle/discipline.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/discipline.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
