Add restrictions for social media

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -120,6 +120,9 @@ main() {
     "upstream")
       upstream
       ;;
+    "social-media")
+      social_media
+      ;;
     "vod")
       vod
       ;;
@@ -726,6 +729,29 @@ upstream() {
       # remove-dnsmasq-toggle-conf private nordvpn_upstream    --skip
       # remove-dnsmasq-toggle-conf private superman_upstream   --skip
       # create-dnsmasq-toggle-conf private adguard_upstream
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+social_media() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$PURPLE_KRYPTONITE" = "1" ] || [ "$RED_KRYPTONITE" = "1" ] || [ "$YELLOW_KRYPTONITE" = "1" ]; then
+        cron-daemonctl stop observe-social-media-conf "$safe"
+        return
+      fi
+
+      cron-daemonctl start observe-social-media-conf "$safe"
+      create-dnsmasq-toggle-conf public social_media
+      ;;
+    "allow")
+      cron-daemonctl stop observe-social-media-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -81,6 +81,9 @@ main() {
       "gaming")
         gaming
         ;;
+      "social-media")
+        social_media
+        ;;
       "vod")
         vod
         ;;
@@ -209,6 +212,10 @@ all() {
 
   if [ -L /etc/dnsmasq.toggle/gaming.conf ]; then
     sudo unlink /etc/dnsmasq.toggle/gaming.conf
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/social_media.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/social_media.conf
   fi
 
   if [ -L /etc/dnsmasq.toggle/vod.conf ]; then
@@ -352,6 +359,14 @@ all() {
   if [ -L /etc/dnsmasq.toggle/gaming.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/gaming.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    # exit
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/social_media.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/social_media.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     # exit
@@ -813,6 +828,37 @@ gaming() {
   if [ -L /etc/dnsmasq.toggle/gaming.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/gaming.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+social_media() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  if [ -L /etc/dnsmasq.priv/toggle/ometeotl.conf ]; then
+    sudo unlink /etc/dnsmasq.priv/toggle/ometeotl.conf
+  fi
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/social_media.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.priv/toggle/ometeotl.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/ometeotl.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/social_media.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/social_media.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
