Add YouTube Music Persistent

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -132,6 +132,9 @@ main() {
     "youtube-music")
       youtube_music
       ;;
+    "youtube-music-persistent")
+      youtube_music_persistent
+      ;;
     *)
       echo "error: no such service: \"$service\"" >&2
       exit 1
@@ -823,6 +826,30 @@ youtube_music() {
       cron-daemonctl stop observe-youtube-music-conf "$safe"
       # create-dnsmasq-toggle-conf public youtube_music
       # create-iptables-toggle-conf public 135_youtube_music
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+youtube_music_persistent() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$PURPLE_KRYPTONITE" = "1" ] || [ "$RED_KRYPTONITE" = "1" ] || [ "$YELLOW_KRYPTONITE" = "1" ]; then
+        cron-daemonctl stop observe-youtube-music-persistent-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-youtube-music-persistent-conf "$safe"
+      remove-dnsmasq-toggle-conf public youtube_music_persistent
+      ;;
+    "allow")
+      :
+      cron-daemonctl stop observe-youtube-music-persistent-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -93,6 +93,9 @@ main() {
       "youtube-music")
         youtube_music
         ;;
+      "youtube-music-persistent")
+        youtube_music_persistent
+        ;;
       "adguard-upstream")
         adguard_upstream
         ;;
@@ -219,6 +222,10 @@ all() {
 
   if ! [ -L /etc/dnsmasq.toggle/youtube_music.conf ]; then
     sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/youtube_music.conf /etc/dnsmasq.toggle
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/youtube_music_persistent.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/youtube_music_persistent.conf /etc/dnsmasq.toggle
   fi
 
   if ! [ -L /etc/dnsmasq.priv/toggle/adguard_upstream.conf ]; then
@@ -370,6 +377,14 @@ all() {
   if ! [ -L /etc/dnsmasq.toggle/youtube_music.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/youtube_music.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    # exit
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/youtube_music_persistent.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/youtube_music_persistent.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     # exit
@@ -873,6 +888,26 @@ youtube_music() {
   if ! [ -L /etc/dnsmasq.toggle/youtube_music.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/youtube_music.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+youtube_music_persistent() {
+  reference_minute=5
+  waiting_interval=1
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/youtube_music_persistent.conf /etc/dnsmasq.toggle
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if ! [ -L /etc/dnsmasq.toggle/youtube_music_persistent.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/youtube_music_persistent.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
