Welcome, Maeve!
The schedule is preliminary.

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -44,6 +44,9 @@ main() {
     "github-editor")
       github_editor
       ;;
+    "maeve")
+      maeve
+      ;;
     "morning")
       morning
       ;;
@@ -287,6 +290,22 @@ github_editor() {
     "allow")
       cron-daemonctl stop observe-github-editor-conf "$safe"
       remove-dnsmasq-toggle-conf public github_editor
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+maeve() {
+  case "$operation" in
+    "deny")
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-maeve-conf "$safe"
+      create-dnsmasq-toggle-conf private maeve
+      ;;
+    "allow")
+      cron-daemonctl stop observe-maeve-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -61,6 +61,9 @@ main() {
     "snorlax")
       snorlax
       ;;
+    "maeve")
+      maeve
+      ;;
     "netflix")
       netflix
       ;;
@@ -265,6 +268,25 @@ snorlax() {
   fi
 }
 
+maeve() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.priv/toggle/maeve.conf
+  no_color
+
+  pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.priv/toggle/maeve.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/maeve.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
 netflix() {
   reference_minute=60
   [ "$DRY_RUN" = 1 ] && exit 0
@@ -326,6 +348,10 @@ ometeotl() {
 superman() {
   [ "$DRY_RUN" = 1 ] && exit 0
 
+  if [ -L /etc/dnsmasq.priv/toggle/maeve.conf ]; then
+    sudo unlink /etc/dnsmasq.priv/toggle/maeve.conf
+  fi
+
   if [ -L /etc/dnsmasq.priv/toggle/ometeotl.conf ]; then
     sudo unlink /etc/dnsmasq.priv/toggle/ometeotl.conf
   fi
@@ -343,6 +369,14 @@ superman() {
   no_color
 
   pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.priv/toggle/maeve.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/maeve.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
 
   if [ -L /etc/dnsmasq.priv/toggle/ometeotl.conf ]; then
     error_color
