Add night mode

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -90,6 +90,9 @@ main() {
     "todo")
       todo
       ;;
+    "todo-night")
+      todo_night
+      ;;
     "upstream")
       upstream
       ;;
@@ -545,6 +548,23 @@ todo() {
     "stop")
       cron-daemonctl stop observe-dnsmasq-todo-list "$safe"
       cron-daemonctl stop observe-dnsmasq-priv-todo-list "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+todo_night() {
+  case "$operation" in
+    "start")
+      cron-daemonctl start observe-dnsmasq-todo-list-night "$safe"
+      cron-daemonctl start observe-dnsmasq-priv-todo-list-night "$safe"
+      ;;
+    "stop")
+      cron-daemonctl stop observe-dnsmasq-todo-list-night "$safe"
+      cron-daemonctl stop observe-dnsmasq-priv-todo-list-night "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
