Create new services: VOD/Netflix Accessories

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -132,6 +132,9 @@ main() {
     "netflix")
       netflix
       ;;
+    "netflix-accessories")
+      netflix_accessories
+      ;;
     "observe")
       observe
       ;;
@@ -174,6 +177,9 @@ main() {
       ;;
     "vod")
       vod
+      ;;
+    "vod-accessories")
+      vod_accessories
       ;;
     "nicovideo")
       nicovideo
@@ -680,6 +686,29 @@ netflix() {
   esac
 }
 
+netflix_accessories() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$(is_any_kryptonite)" = "true" ]; then
+        cron-daemonctl stop observe-netflix-accessories-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-netflix-accessories-conf "$safe"
+      create-dnsmasq-toggle-conf public netflix_accessories
+      ;;
+    "allow")
+      cron-daemonctl stop observe-netflix-accessories-conf "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
 observe() {
   case "$operation" in
     "start")
@@ -1069,6 +1098,29 @@ vod() {
       cron-daemonctl stop observe-vod-conf "$safe"
       # remove-dnsmasq-toggle-conf public vod
       # remove-iptables-toggle-conf public 133_vod
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+vod_accessories() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$(is_any_kryptonite)" = "true" ]; then
+        cron-daemonctl stop observe-vod-accessories-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-vod-accessories-conf "$safe"
+      create-dnsmasq-toggle-conf public vod_accessories
+      ;;
+    "allow")
+      cron-daemonctl stop observe-vod-accessories-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
