Add rules for YouTube Alternative

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -64,6 +64,9 @@ main() {
     "youtube")
       youtube
       ;;
+    "youtube-alternative")
+      youtube_alternative
+      ;;
     "youtube-music")
       youtube_music
       ;;
@@ -355,6 +358,21 @@ youtube() {
       cron-daemonctl stop observe-youtube-conf "$safe"
       # sudo remove-dnsmasq-toggle-conf public youtube
       # remove-iptables-toggle-conf public 134_youtube
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+youtube_alternative() {
+  case "$operation" in
+    "deny")
+      sudo remove-dnsmasq-toggle-conf public youtube_alternative
+      ;;
+    "allow")
+      :
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
