Introduce Snorlax (Sleep)

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -65,6 +65,9 @@ main() {
     "periodic")
       periodic
       ;;
+    "snorlax")
+      snorlax
+      ;;
     "startup")
       startup
       ;;
@@ -363,6 +366,23 @@ periodic() {
   auto-git-pull
 
   digital-detox-notifier
+}
+
+snorlax() {
+  case "$operation" in
+    "deny")
+      # cron-daemonctl start observe-snorlax-conf "$safe"
+      create-dnsmasq-toggle-conf public snorlax
+      ;;
+    "allow")
+      # cron-daemonctl stop observe-snorlax-conf "$safe"
+      remove-dnsmasq-toggle-conf public snorlax
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
 }
 
 startup() {
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -58,6 +58,9 @@ main() {
     "focus")
       focus
       ;;
+    "snorlax")
+      snorlax
+      ;;
     "netflix")
       netflix
       ;;
@@ -231,6 +234,25 @@ focus() {
   if [ -L /etc/dnsmasq.priv/toggle/focus.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.priv/toggle/focus.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+snorlax() {
+  reference_minute=1
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/snorlax.conf
+  no_color
+
+  pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.toggle/snorlax.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/snorlax.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
