Add new network restriction: Athena

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -105,6 +105,9 @@ main() {
     "knock")
       knock
       ;;
+    "athena")
+      athena
+      ;;
     "minerva")
       minerva
       ;;
@@ -535,6 +538,29 @@ knock() {
       ;;
     "allow")
       cron-daemonctl stop observe-knock-conf "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+athena() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$(is_any_kryptonite)" = "true" ]; then
+        cron-daemonctl stop observe-athena-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-athena-conf "$safe"
+      create-dnsmasq-toggle-conf public athena
+      ;;
+    "allow")
+      cron-daemonctl stop observe-athena-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -106,6 +106,9 @@ main() {
         "knock")
           knock
           ;;
+        "athena")
+          athena
+          ;;
         "minerva")
           minerva
           ;;
@@ -268,6 +271,10 @@ all() {
 
   if ! [ -L /etc/dnsmasq.toggle/knock.conf ]; then
     sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/knock.conf /etc/dnsmasq.toggle
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/athena.conf
   fi
 
   if [ -L /etc/dnsmasq.toggle/minerva.conf ]; then
@@ -461,6 +468,14 @@ all() {
   if ! [ -L /etc/dnsmasq.toggle/knock.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/knock.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/athena.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1067,6 +1082,26 @@ knock() {
   if ! [ -L "/etc/dnsmasq.toggle/knock.conf" ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/knock.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+athena() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/athena.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/athena.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
