Create new service: Siren

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -101,6 +101,9 @@ main() {
     "knock")
       knock
       ;;
+    "siren")
+      siren
+      ;;
     "minerva")
       minerva
       ;;
@@ -508,6 +511,29 @@ knock() {
       ;;
     "allow")
       cron-daemonctl stop observe-knock-conf "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+siren() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$(is_any_kryptonite)" = "true" ]; then
+        cron-daemonctl stop observe-siren-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-siren-conf "$safe"
+      remove-dnsmasq-toggle-conf public siren
+      ;;
+    "allow")
+      cron-daemonctl stop observe-siren-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -103,6 +103,9 @@ main() {
         "knock")
           knock
           ;;
+        "siren")
+          siren
+          ;;
         "minerva")
           minerva
           ;;
@@ -261,6 +264,10 @@ all() {
 
   if ! [ -L /etc/dnsmasq.toggle/knock.conf ]; then
     sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/knock.conf /etc/dnsmasq.toggle
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/siren.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/siren.conf /etc/dnsmasq.toggle
   fi
 
   if [ -L /etc/dnsmasq.toggle/minerva.conf ]; then
@@ -446,6 +453,14 @@ all() {
   if ! [ -L /etc/dnsmasq.toggle/knock.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/knock.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/siren.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/siren.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1030,6 +1045,28 @@ knock() {
   if ! [ -L "/etc/dnsmasq.toggle/knock.conf" ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/knock.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+siren() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  while ! [ -L "/etc/dnsmasq.toggle/siren.conf" ]; do
+    warning_color
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/siren.conf /etc/dnsmasq.toggle
+    no_color
+
+    pause "$waiting_interval" "$WAITING_MESSAGE"
+  done
+
+  if ! [ -L "/etc/dnsmasq.toggle/siren.conf" ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/siren.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
