Add new restriction: YouTube Accessories

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -136,6 +136,9 @@ main() {
     "youtube")
       youtube
       ;;
+    "youtube-accessories")
+      youtube_accessories
+      ;;
     "youtube-alternative")
       youtube_alternative
       ;;
@@ -889,6 +892,29 @@ youtube() {
       cron-daemonctl stop observe-youtube-conf "$safe"
       # remove-dnsmasq-toggle-conf public youtube
       # remove-iptables-toggle-conf public 134_youtube
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+youtube_accessories() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$PURPLE_KRYPTONITE" = "1" ] || [ "$RED_KRYPTONITE" = "1" ] || [ "$YELLOW_KRYPTONITE" = "1" ]; then
+        cron-daemonctl stop observe-youtube-accessories-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-youtube-accessories-conf "$safe"
+      create-dnsmasq-toggle-conf public youtube_accessories
+      ;;
+    "allow")
+      cron-daemonctl stop observe-youtube-accessories-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -108,6 +108,9 @@ main() {
         "youtube")
           youtube
           ;;
+        "youtube-accessories")
+          youtube_accessories
+          ;;
         "youtube-alternative")
           youtube_alternative
           ;;
@@ -253,6 +256,10 @@ all() {
 
   if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
     sudo unlink /etc/dnsmasq.toggle/youtube.conf
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/youtube_accessories.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/youtube_accessories.conf
   fi
 
   if ! [ -L /etc/dnsmasq.toggle/youtube_alternative.conf ]; then
@@ -430,6 +437,14 @@ all() {
   if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/youtube.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/youtube_accessories.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/youtube_accessories.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -979,6 +994,65 @@ youtube() {
   if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/youtube.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+youtube_accessories() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  if [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
+    sudo unlink /etc/dnsmasq.priv/toggle/superman_upstream.conf
+  fi
+
+  if ! [ -L /etc/dnsmasq.priv/toggle/adguard_upstream.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.priv/toggle/adguard_upstream.conf /etc/dnsmasq.priv/toggle
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/youtube.conf
+  fi
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/youtube_accessories.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/superman_upstream.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if ! [ -L /etc/dnsmasq.priv/toggle/adguard_upstream.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/adguard_upstream.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/youtube.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/youtube_accessories.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/youtube_accessories.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
