Create new service: nicovideo-accessories

diff --git a/raspberrypi/bin/scheduler b/raspberrypi/bin/scheduler
--- a/raspberrypi/bin/scheduler
+++ b/raspberrypi/bin/scheduler
@@ -178,6 +178,9 @@ main() {
     "nicovideo")
       nicovideo
       ;;
+    "nicovideo-accessories")
+      nicovideo_accessories
+      ;;
     "youtube")
       youtube
       ;;
@@ -1094,6 +1097,29 @@ nicovideo() {
     "allow")
       cron-daemonctl stop observe-nicovideo-conf "$safe"
       cron-daemonctl stop observe-nicovideo-allow-conf "$safe"
+      ;;
+    *)
+      echo "error: no such operation: \"$operation\"" >&2
+      exit 1
+      ;;
+  esac
+}
+
+nicovideo_accessories() {
+  case "$operation" in
+    "deny")
+      if { [ "$VAMPIRE" = "1" ] && [ "$(garnish savor)" -gt 0 ] && [ "$MORNING" != "-1" ]; } ||
+      [ "$MORNING" = "1" ] || [ "$VAMPIRE" = "-1" ] ||
+      [ "$(is_any_kryptonite)" = "true" ]; then
+        cron-daemonctl stop observe-nicovideo-accessories-conf "$safe"
+        return
+      fi
+
+      [ "$SOFT" = 1 ] || cron-daemonctl start observe-nicovideo-accessories-conf "$safe"
+      create-dnsmasq-toggle-conf public nicovideo_accessories
+      ;;
+    "allow")
+      cron-daemonctl stop observe-nicovideo-accessories-conf "$safe"
       ;;
     *)
       echo "error: no such operation: \"$operation\"" >&2
diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -124,6 +124,9 @@ main() {
         "nicovideo")
           nicovideo
           ;;
+        "nicovideo-accessories")
+          nicovideo_accessories
+          ;;
         "youtube")
           youtube
           ;;
@@ -306,6 +309,10 @@ all() {
 
   if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
     sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/nicovideo_allow.conf /etc/dnsmasq.toggle
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo_accessories.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/nicovideo_accessories.conf
   fi
 
   if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
@@ -547,6 +554,14 @@ all() {
   if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/nicovideo_allow.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo_accessories.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo_accessories.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1288,6 +1303,52 @@ nicovideo() {
   if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/nicovideo.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+nicovideo_accessories() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/nicovideo.conf
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/nicovideo_allow.conf /etc/dnsmasq.toggle
+  fi
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/nicovideo_accessories.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo_allow.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo_accessories.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo_accessories.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
