Return given value when passed or failed (ticksum)

diff --git a/raspberrypi/bin/ticksum b/raspberrypi/bin/ticksum
--- a/raspberrypi/bin/ticksum
+++ b/raspberrypi/bin/ticksum
@@ -9,11 +9,22 @@ main() {
 
   keywords=$(printf '%s\n' "$@" | paste -sd '|')
   pattern='\\*\\s*\\[x\\].*\\[('"$keywords"')\\]\\(https://github.com/noraworld/diary-templates/issues/[0-9]*\\)'
-  [ "$DEBUG" = "1" ] && echo "keywords: $keywords" >&2
-  [ "$DEBUG" = "1" ] && echo "pattern:  $pattern"  >&2
-  [ "$DEBUG" = "1" ] && echo "past:     $PAST"     >&2
 
-  eval "todo-cache --repo $REPO --past $PAST | grep -cE \"$pattern\"" || true
+  passed_count=$(eval "todo-cache --repo $REPO --past $PAST | grep -cE \"$pattern\"" || true)
+
+  [ "$DEBUG" = "1" ] && echo "DEBUG: keywords: $keywords"     >&2
+  [ "$DEBUG" = "1" ] && echo "DEBUG: pattern:  $pattern"      >&2
+  [ "$DEBUG" = "1" ] && echo "DEBUG: past:     $PAST"         >&2
+  [ "$DEBUG" = "1" ] && echo "DEBUG: argc:     $#"            >&2
+  [ "$DEBUG" = "1" ] && echo "DEBUG: passed:   $passed_count" >&2
+
+  if [ "$PASS_STAMP" = "" ] || [ "$FAIL_STAMP" = "" ]; then
+    echo "$passed_count"
+  elif [ "$#" -eq "$passed_count" ]; then
+    echo "$PASS_STAMP"
+  else
+    echo "$FAIL_STAMP"
+  fi
 }
 
 validate() {
@@ -25,17 +36,27 @@ validate() {
   if [ "$PAST" = "" ]; then
     PAST=0
   fi
+
+  if \
+    { [ "$PASS_STAMP" != "" ] && [ "$FAIL_STAMP"  = "" ]; } ||
+    { [ "$PASS_STAMP"  = "" ] && [ "$FAIL_STAMP" != "" ]; }
+  then
+    echo "both --pass-stamp and --fail-stamp are necessary" >&2
+    exit 1
+  fi
 }
 
 # @getoptions
 parser_definition() {
   setup   REST help:usage -- "Usage: ticksum [options]... [arguments]..." ''
   msg -- 'Options:'
-  flag    DEBUG      --debug   -- "debug"
-  param   PAST       --past    -- "past (default: 0)"
-  param   REPO       --repo    -- "repo"
-  disp    :usage  -h --help
-  disp    VERSION    --version
+  flag    DEBUG         --debug      -- "debug"
+  param   FAIL_STAMP    --fail-stamp -- "return a given value instead of the number of checked tasks when not all the tasks have been passed"
+  param   PASS_STAMP    --pass-stamp -- "return a given value instead of the number of checked tasks when all the tasks have been passed"
+  param   PAST          --past       -- "past (default: 0)"
+  param   REPO          --repo       -- "repo"
+  disp    :usage     -h --help
+  disp    VERSION       --version
 }
 # @end
 
@@ -43,6 +64,8 @@ parser_definition() {
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
 DEBUG=''
+FAIL_STAMP=''
+PASS_STAMP=''
 PAST=''
 REPO=''
 REST=''
@@ -64,6 +87,16 @@ parse() {
         eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
         DEBUG="$OPTARG"
         ;;
+      '--fail-stamp')
+        [ $# -le 1 ] && set "required" "$1" && break
+        OPTARG=$2
+        FAIL_STAMP="$OPTARG"
+        shift ;;
+      '--pass-stamp')
+        [ $# -le 1 ] && set "required" "$1" && break
+        OPTARG=$2
+        PASS_STAMP="$OPTARG"
+        shift ;;
       '--past')
         [ $# -le 1 ] && set "required" "$1" && break
         OPTARG=$2
@@ -111,6 +144,8 @@ Usage: ticksum [options]... [arguments]...
 
 Options:
       --debug                 debug
+      --fail-stamp FAIL_STAMP return a given value instead of the number of checked tasks when not all the tasks have been passed
+      --pass-stamp PASS_STAMP return a given value instead of the number of checked tasks when all the tasks have been passed
       --past PAST             past (default: 0)
       --repo REPO             repo
   -h, --help
