Replace noraworld/diary-templates with argument parameter in ticksum

diff --git a/raspberrypi/bin/ticksum b/raspberrypi/bin/ticksum
--- a/raspberrypi/bin/ticksum
+++ b/raspberrypi/bin/ticksum
@@ -22,9 +22,9 @@ main() {
   fi
 
   keywords=$(printf '%s\n' "$@" | paste -sd '|')
-  pattern='\\*\\s*\\[x\\].*\\[('"$keywords"')\\]\\(https://github.com/noraworld/diary-templates/issues/[0-9]*\\)'
+  pattern='\\*\\s*\\[x\\].*\\[('"$keywords"')\\]\\(https://github.com/'"$TEMPLATE_REPO"'/issues/[0-9]*\\)'
 
-  passed_count=$(eval "todo-cache --repo $REPO --past $PAST $force $cache_only | grep -cE \"$pattern\"" || true)
+  passed_count=$(eval "todo-cache --repo $MAIN_REPO --past $PAST $force $cache_only | grep -cE \"$pattern\"" || true)
 
   [ "$DEBUG" = "1" ] && echo "DEBUG: keywords: $keywords"     >&2
   [ "$DEBUG" = "1" ] && echo "DEBUG: pattern:  $pattern"      >&2
@@ -61,8 +61,13 @@ print_result_end_exit() {
 }
 
 validate() {
-  if [ "$REPO" = "" ]; then
-    echo "--repo is missing" >&2
+  if [ "$MAIN_REPO" = "" ]; then
+    echo "--main-repo is missing" >&2
+    exit 1
+  fi
+
+  if [ "$TEMPLATE_REPO" = "" ]; then
+    echo "--template-repo is missing" >&2
     exit 1
   fi
 
@@ -84,7 +89,8 @@ parser_definition() {
   flag    CACHE_ONLY    --cache-only   -- "use cache even if cache is stale (ignore check interval)"
   param   PASS_STAMP    --pass-stamp   -- "[PRIORITY:2] return a given value instead of the number of checked tasks when all the tasks have been passed"
   param   PAST          --past         -- "past (default: 0)"
-  param   REPO          --repo         -- "repo"
+  param   MAIN_REPO     --main-repo     -- "main repo"
+  param   TEMPLATE_REPO --template-repo -- "template repo"
   param   ZERO_STAMP    --zero-stamp   -- "[PRIORITY:1] return a given value instead of zero (none of the tasks has not been accomplished)"
   disp    :usage     -h --help
   disp    VERSION       --version
@@ -96,7 +102,7 @@ parser_definition() {
 
 # @gengetoptions parser -i parser_definition parse
 # Generated by getoptions (BEGIN)
-# URL: https://github.com/ko1nksm/getoptions (v3.3.0)
+# URL: https://github.com/ko1nksm/getoptions (v3.3.2)
 DEBUG=''
 FAIL_STAMP=''
 FALL_THROUGH=''
@@ -105,12 +111,13 @@ MAXI_STAMP=''
 CACHE_ONLY=''
 PASS_STAMP=''
 PAST=''
-REPO=''
+MAIN_REPO=''
+TEMPLATE_REPO=''
 ZERO_STAMP=''
 REST=''
 parse() {
   OPTIND=$(($#+1))
-  while OPTARG= && [ $# -gt 0 ]; do
+  while OPTARG= && [ "${REST}" != x ] && [ $# -gt 0 ]; do
     case $1 in
       --?*=*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
@@ -118,7 +125,7 @@ parse() {
       --no-*|--without-*) unset OPTARG ;;
       -[h]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
-        OPTARG= ;;
+        case $2 in --*) set -- "$1" unknown "$2" && REST=x; esac;OPTARG= ;;
     esac
     case $1 in
       '--debug')
@@ -161,10 +168,15 @@ parse() {
         OPTARG=$2
         PAST="$OPTARG"
         shift ;;
-      '--repo')
+      '--main-repo')
         [ $# -le 1 ] && set "required" "$1" && break
         OPTARG=$2
-        REPO="$OPTARG"
+        MAIN_REPO="$OPTARG"
+        shift ;;
+      '--template-repo')
+        [ $# -le 1 ] && set "required" "$1" && break
+        OPTARG=$2
+        TEMPLATE_REPO="$OPTARG"
         shift ;;
       '--zero-stamp')
         [ $# -le 1 ] && set "required" "$1" && break
@@ -215,7 +227,9 @@ Options:
       --cache-only            use cache even if cache is stale (ignore check interval)
       --pass-stamp PASS_STAMP [PRIORITY:2] return a given value instead of the number of checked tasks when all the tasks have been passed
       --past PAST             past (default: 0)
-      --repo REPO             repo
+      --main-repo MAIN_REPO   main repo
+      --template-repo TEMPLATE_REPO
+                              template repo
       --zero-stamp ZERO_STAMP [PRIORITY:1] return a given value instead of zero (none of the tasks has not been accomplished)
   -h, --help
       --version
