Allow normal and exclusion mode to be used together
https://github.com/noraworld/to-do/issues/1063

diff --git a/raspberrypi/bin/todo-accomplished b/raspberrypi/bin/todo-accomplished
--- a/raspberrypi/bin/todo-accomplished
+++ b/raspberrypi/bin/todo-accomplished
@@ -9,12 +9,11 @@ export GHC_FROM="$(basename "$0") $*"
 main() {
   parse "$@"
   eval "set -- $REST"
+  validate "$@"
 
-  [ "$PAST"     = "" ] && PAST=0
-  [ "$REPO"     = "" ] && echo "error: --repo is missing" >&2 && exit 1
-  [ "$RETRY"    = "" ] && RETRY=5
-  [ "$SLEEP"    = "" ] && SLEEP=3
-  [ "$STANDARD" = "" ] && STANDARD=3
+  [ "$PAST"  = "" ] && PAST=0
+  [ "$RETRY" = "" ] && RETRY=5
+  [ "$SLEEP" = "" ] && SLEEP=3
 
   count=0
   while [ "$body" = "" ] && [ "$count" -lt "$RETRY" ]; do
@@ -40,32 +39,35 @@ main() {
     sleep "$SLEEP"
   done
 
+  checked_count=$(  echo "$body" | grep -c "\[x\]")
+  unchecked_count=$(echo "$body" | grep -c "\[ \]")
   result="unknown"
-  if [ "$PAST" -ge 1 ] && [ "$past_body" != "" ] && [ "$(echo "$past_body" | grep -c "\[ \]")" -ne 0 ]; then
+
+  if [ "$body" = "" ] || { [ "$PAST" -ge 1 ] && [ "$past_body" = "" ]; }; then
+    result="failed to fetch"
+    echo "0"
+  elif [ "$PAST" -ge 1 ] && [ "$past_body" != "" ] && [ "$(echo "$past_body" | grep -c "\[ \]")" -ne 0 ]; then
     result="not accomplished in the past"
     echo "-1"
-  elif [ "$EXCEPT" = "" ]; then
-    if [ "$body" = "" ]; then
-      result="failed to fetch"
-      echo "0"
-    elif [ "$(echo "$body" | grep -c "\[x\]")" -ge "$STANDARD" ]; then
-      result="accomplished"
-      echo "1"
-    else
-      result="not accomplished"
-      echo "-1"
-    fi
+  elif {
+    [ "$CHECKED"   != "" ]                &&
+    [ "$UNCHECKED" != "" ]                &&
+    [ "$checked_count"   -ge "$CHECKED" ] &&
+    [ "$unchecked_count" -le "$UNCHECKED" ];
+  } || {
+    [ "$CHECKED"   != "" ] &&
+    [ "$UNCHECKED"  = "" ] &&
+    [ "$checked_count" -ge "$CHECKED" ];
+  } || {
+    [ "$UNCHECKED" != "" ] &&
+    [ "$CHECKED"    = "" ] &&
+    [ "$unchecked_count" -le "$UNCHECKED" ];
+  }; then
+    result="accomplished"
+    echo "1"
   else
-    if [ "$body" = "" ]; then
-      result="failed to fetch"
-      echo "0"
-    elif [ "$(echo "$body" | grep -c "\[ \]")" -le "$STANDARD" ]; then
-      result="accomplished"
-      echo "1"
-    else
-      result="not accomplished"
-      echo "-1"
-    fi
+    result="not accomplished"
+    echo "-1"
   fi
 
   echo "[$(date '+%Y-%m-%dT%H:%M:%S%z')] Invoked GitHub API with result \"$result\"" >> "$LOG_PATH"
@@ -77,30 +79,42 @@ main() {
   fi
 }
 
+validate() {
+  if [ "$REPO" = "" ]; then
+    echo "error: --repo is missing" >&2
+    exit 1
+  fi
+
+  if [ "$CHECKED" = "" ] && [ "$UNCHECKED" = "" ]; then
+    echo "error: both --checked and --unchecked not specified is not acceptable" >&2
+    exit 1
+  fi
+}
+
 # @getoptions
 parser_definition() {
   setup   REST help:usage -- "Usage: todo-accomplished [options]... [arguments]..." ''
   msg -- 'Options:'
-  flag    EXCEPT      --except   -- "count how many to-dos have not been accomplished yet rather than accomplished"
-  param   PAST        --past     -- "determine whether to check the past list as well and specify how many days to go back"
-  param   REPO        --repo     -- "a target repository name"
-  param   RETRY       --retry    -- "how many times to retry"
-  param   SLEEP       --sleep    -- "how many seconds to wait before retrying the next one"
-  param   STANDARD    --standard -- "how many to-dos to need"
-  disp    :usage   -h --help     -- "show help message and exit"
-  disp    VERSION     --version  -- "show current version"
+  param   CHECKED      --checked   -- "count how many to-dos have been accomplished (it is possible to use this with --unchecked together)"
+  param   PAST         --past      -- "determine whether to check the past list as well and specify how many days to go back"
+  param   REPO         --repo      -- "a target repository name"
+  param   RETRY        --retry     -- "how many times to retry"
+  param   SLEEP        --sleep     -- "how many seconds to wait before retrying the next one"
+  param   UNCHECKED    --unchecked -- "count how many to-dos have NOT been accomplished yet (it is possible to use this with --checked together)"
+  disp    :usage    -h --help      -- "show help message and exit"
+  disp    VERSION      --version   -- "show current version"
 }
 # @end
 
 # @gengetoptions parser -i parser_definition parse
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
-EXCEPT=''
+CHECKED=''
 PAST=''
 REPO=''
 RETRY=''
 SLEEP=''
-STANDARD=''
+UNCHECKED=''
 REST=''
 parse() {
   OPTIND=$(($#+1))
@@ -115,11 +129,11 @@ parse() {
         OPTARG= ;;
     esac
     case $1 in
-      '--except')
-        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
-        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
-        EXCEPT="$OPTARG"
-        ;;
+      '--checked')
+        [ $# -le 1 ] && set "required" "$1" && break
+        OPTARG=$2
+        CHECKED="$OPTARG"
+        shift ;;
       '--past')
         [ $# -le 1 ] && set "required" "$1" && break
         OPTARG=$2
@@ -140,10 +154,10 @@ parse() {
         OPTARG=$2
         SLEEP="$OPTARG"
         shift ;;
-      '--standard')
+      '--unchecked')
         [ $# -le 1 ] && set "required" "$1" && break
         OPTARG=$2
-        STANDARD="$OPTARG"
+        UNCHECKED="$OPTARG"
         shift ;;
       '-h'|'--help')
         usage
@@ -181,12 +195,12 @@ cat<<'GETOPTIONSHERE'
 Usage: todo-accomplished [options]... [arguments]...
 
 Options:
-      --except                count how many to-dos have not been accomplished yet rather than accomplished
+      --checked CHECKED       count how many to-dos have been accomplished (it is possible to use this with --unchecked together)
       --past PAST             determine whether to check the past list as well and specify how many days to go back
       --repo REPO             a target repository name
       --retry RETRY           how many times to retry
       --sleep SLEEP           how many seconds to wait before retrying the next one
-      --standard STANDARD     how many to-dos to need
+      --unchecked UNCHECKED   count how many to-dos have NOT been accomplished yet (it is possible to use this with --checked together)
   -h, --help                  show help message and exit
       --version               show current version
 GETOPTIONSHERE
