Add options --skip & --sleep for trailblazer

diff --git a/raspberrypi/bin/trailblazer b/raspberrypi/bin/trailblazer
--- a/raspberrypi/bin/trailblazer
+++ b/raspberrypi/bin/trailblazer
@@ -1,15 +1,108 @@
 #!/bin/sh
 
-SLEEP_INTERVAL="10"
-
 main() {
-  while [ "$(todo-accomplished --repo "noraworld/diary" --retry 1 --past 0 --standard 10)" -le 0 ]; do
-    echo "Failed to retrieve todo list. Retry in $SLEEP_INTERVAL seconds."
-    sleep "$SLEEP_INTERVAL"
-  done
+  parse "$@"
+  eval "set -- $REST"
+
+  sleep_interval=10
+  if [ "$SLEEP" != "" ]; then
+    sleep_interval="$SLEEP"
+  fi
+
+  if [ "$SKIP" != 1 ]; then
+    while [ "$(todo-accomplished --repo "noraworld/diary" --retry 1 --past 0 --standard 10)" -le 0 ]; do
+      echo "Failed to retrieve todo list. Retry in $sleep_interval seconds."
+      sleep "$sleep_interval"
+    done
+  fi
 
   unlock all --skip
   ls --color=auto --literal -al /etc/dnsmasq.toggle && ls --color=auto --literal -al /etc/dnsmasq.priv/toggle
 }
+
+# @getoptions
+parser_definition() {
+  setup   REST help:usage -- "Usage: trailblazer [options]... [arguments]..." ''
+  msg -- 'Options:'
+  flag    SKIP       --skip  -- "skip todo-accomplished"
+  param   SLEEP      --sleep -- "how many seconds to wait for the next attempt"
+  disp    :usage  -h --help
+  disp    VERSION    --version
+}
+# @end
+
+# @gengetoptions parser -i parser_definition parse
+# Generated by getoptions (BEGIN)
+# URL: https://github.com/ko1nksm/getoptions (v3.3.0)
+SKIP=''
+SLEEP=''
+REST=''
+parse() {
+  OPTIND=$(($#+1))
+  while OPTARG= && [ $# -gt 0 ]; do
+    case $1 in
+      --?*=*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
+        ;;
+      --no-*|--without-*) unset OPTARG ;;
+      -[h]?*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
+        OPTARG= ;;
+    esac
+    case $1 in
+      '--skip')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
+        SKIP="$OPTARG"
+        ;;
+      '--sleep')
+        [ $# -le 1 ] && set "required" "$1" && break
+        OPTARG=$2
+        SLEEP="$OPTARG"
+        shift ;;
+      '-h'|'--help')
+        usage
+        exit 0 ;;
+      '--version')
+        echo "${VERSION}"
+        exit 0 ;;
+      --)
+        shift
+        while [ $# -gt 0 ]; do
+          REST="${REST} \"\${$(($OPTIND-$#))}\""
+          shift
+        done
+        break ;;
+      [-]?*) set "unknown" "$1"; break ;;
+      *)
+        REST="${REST} \"\${$(($OPTIND-$#))}\""
+    esac
+    shift
+  done
+  [ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
+  case $1 in
+    unknown) set "Unrecognized option: $2" "$@" ;;
+    noarg) set "Does not allow an argument: $2" "$@" ;;
+    required) set "Requires an argument: $2" "$@" ;;
+    pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
+    notcmd) set "Not a command: $2" "$@" ;;
+    *) set "Validation error ($1): $2" "$@"
+  esac
+  echo "$1" >&2
+  exit 1
+}
+usage() {
+cat<<'GETOPTIONSHERE'
+Usage: trailblazer [options]... [arguments]...
+
+Options:
+      --skip                  skip todo-accomplished
+      --sleep SLEEP           how many seconds to wait for the next attempt
+  -h, --help
+      --version
+GETOPTIONSHERE
+}
+# Generated by getoptions (END)
+# @end
 
 main "$@"
