Create new restriction: athena-allow

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -277,6 +277,10 @@ all() {
     sudo unlink /etc/dnsmasq.toggle/athena.conf
   fi
 
+  if ! [ -L /etc/dnsmasq.toggle/athena_allow.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/athena_allow.conf /etc/dnsmasq.toggle
+  fi
+
   if [ -L /etc/dnsmasq.toggle/minerva.conf ]; then
     sudo unlink /etc/dnsmasq.toggle/minerva.conf
   fi
@@ -476,6 +480,14 @@ all() {
   if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/athena.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/athena_allow.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/athena_allow.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1094,10 +1106,20 @@ athena() {
   [ "$DRY_RUN" = 1 ] && exit 0
 
   warning_color
+  sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/athena_allow.conf /etc/dnsmasq.toggle
   sudo unlink /etc/dnsmasq.toggle/athena.conf
   no_color
 
   pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if ! [ -L /etc/dnsmasq.toggle/athena_allow.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/athena_allow.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
 
   if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
     error_color
