Create new service: nicovideo

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -121,6 +121,9 @@ main() {
         "vod")
           vod
           ;;
+        "nicovideo")
+          nicovideo
+          ;;
         "youtube")
           youtube
           ;;
@@ -295,6 +298,14 @@ all() {
 
   if [ -L /etc/dnsmasq.toggle/vod.conf ]; then
     sudo unlink /etc/dnsmasq.toggle/vod.conf
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/nicovideo.conf
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
+    sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/nicovideo_allow.conf /etc/dnsmasq.toggle
   fi
 
   if [ -L /etc/dnsmasq.toggle/youtube.conf ]; then
@@ -520,6 +531,22 @@ all() {
   if [ -L /etc/dnsmasq.toggle/vod.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/vod.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo_allow.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1231,6 +1258,36 @@ vod() {
   if [ -L /etc/dnsmasq.toggle/vod.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/vod.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+nicovideo() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/nicovideo_allow.conf /etc/dnsmasq.toggle
+  sudo unlink /etc/dnsmasq.toggle/nicovideo.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if ! [ -L /etc/dnsmasq.toggle/nicovideo_allow.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo_allow.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/nicovideo.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/nicovideo.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
