Add ability to unlock upstream

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -127,6 +127,9 @@ main() {
         "youtube-music-persistent")
           youtube_music_persistent
           ;;
+        "upstream")
+          upstream
+          ;;
         "adguard-upstream")
           adguard_upstream
           ;;
@@ -1226,6 +1229,36 @@ youtube_music_persistent() {
   if ! [ -L /etc/dnsmasq.toggle/youtube_music_persistent.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/youtube_music_persistent.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+upstream() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.priv/toggle/superman_upstream.conf
+  sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.priv/toggle/adguard_upstream.conf /etc/dnsmasq.priv/toggle
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.priv/toggle/superman_upstream.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/superman_upstream.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+
+  if ! [ -L /etc/dnsmasq.priv/toggle/adguard_upstream.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/adguard_upstream.conf still doesn't exist" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
