Accept multiple arguments

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -23,7 +23,7 @@ NO_COLOR="\033[0m"
 SKIP=0
 
 main() {
-  service="$1"
+  services=$@
   reference_minute=0
 
   parse "$@"
@@ -38,69 +38,71 @@ main() {
 
   log_before_execution "$@"
 
-  case "$service" in
-    "amazon")
-      amazon
-      ;;
-    "chime")
-      chime
-      ;;
-    "crimson")
-      crimson
-      ;;
-    "deregulated-superman")
-      deregulated_superman
-      ;;
-    "focus")
-      focus
-      ;;
-    "snorlax")
-      snorlax
-      ;;
-    "maeve")
-      maeve
-      ;;
-    "netflix")
-      netflix
-      ;;
-    "ometeotl")
-      ometeotl
-      ;;
-    "superman")
-      superman
-      ;;
-    "gaming")
-      gaming
-      ;;
-    "vod")
-      vod
-      ;;
-    "youtube")
-      youtube
-      ;;
-    "youtube-alternative")
-      youtube_alternative
-      ;;
-    "youtube-music")
-      youtube_music
-      ;;
-    "adguard-upstream")
-      adguard_upstream
-      ;;
-    "cloudflare-upstream")
-      cloudflare_upstream
-      ;;
-    "nordvpn-upstream")
-      nordvpn_upstream
-      ;;
-    "superman-upstream")
-      superman_upstream
-      ;;
-    *)
-      echo "error: no such service $service" >&2
-      exit 1
-      ;;
-  esac
+  for service in $services; do
+    case "$service" in
+      "amazon")
+        amazon
+        ;;
+      "chime")
+        chime
+        ;;
+      "crimson")
+        crimson
+        ;;
+      "deregulated-superman")
+        deregulated_superman
+        ;;
+      "focus")
+        focus
+        ;;
+      "snorlax")
+        snorlax
+        ;;
+      "maeve")
+        maeve
+        ;;
+      "netflix")
+        netflix
+        ;;
+      "ometeotl")
+        ometeotl
+        ;;
+      "superman")
+        superman
+        ;;
+      "gaming")
+        gaming
+        ;;
+      "vod")
+        vod
+        ;;
+      "youtube")
+        youtube
+        ;;
+      "youtube-alternative")
+        youtube_alternative
+        ;;
+      "youtube-music")
+        youtube_music
+        ;;
+      "adguard-upstream")
+        adguard_upstream
+        ;;
+      "cloudflare-upstream")
+        cloudflare_upstream
+        ;;
+      "nordvpn-upstream")
+        nordvpn_upstream
+        ;;
+      "superman-upstream")
+        superman_upstream
+        ;;
+      *)
+        echo "error: no such service $service" >&2
+        exit 1
+        ;;
+    esac
+  done
 
   restart_dnsmasq "$@"
   remaining_time "$@"
@@ -769,9 +771,9 @@ remaining_time() {
       for i in $(seq 0 $(expr "$TIMES" - 1)); do
         # MEMO: if it's executed at any minute 0 seconds on the dot, the schedule time is shifted by 1 minute
         if [ "$DEBUG" = 1 ]; then
-          at_output=$(echo "$PROG_NAME $service --delay $DELAY_INTERVAL --debug >> $LOG_PATH 2>&1" | at now + $(expr "$next_in" + "$i" \* "$reference_minute") min 2>&1)
+          at_output=$(echo "$PROG_NAME $services --delay $DELAY_INTERVAL --debug >> $LOG_PATH 2>&1" | at now + $(expr "$next_in" + "$i" \* "$reference_minute") min 2>&1)
         else
-          at_output=$(echo "$PROG_NAME $service --delay $DELAY_INTERVAL"                           | at now + $(expr "$next_in" + "$i" \* "$reference_minute") min 2>&1)
+          at_output=$(echo "$PROG_NAME $services --delay $DELAY_INTERVAL"                           | at now + $(expr "$next_in" + "$i" \* "$reference_minute") min 2>&1)
         fi
 
         [ "$VERBOSE" = 1 ] && echo "$at_output" | grep -Ev "^warning: commands will be executed using"
