Add "focus" to "unlock"

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -35,6 +35,9 @@ main() {
     "deregulated-superman")
       deregulated_superman
       ;;
+    "focus")
+      focus
+      ;;
     "netflix")
       netflix
       ;;
@@ -147,6 +150,27 @@ deregulated_superman() {
   if [ -L /etc/dnsmasq.priv/toggle/deregulated_superman.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.priv/toggle/deregulated_superman.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    exit
+  fi
+}
+
+focus() {
+  reference_minute=5
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.priv/toggle/focus.conf
+  no_color
+
+  if [ "$(is_observer_active "focus")" = "active" ]; then
+    pause "$WAITING_INTERVAL" "$WAITING_MESSAGE"
+  fi
+
+  if [ -L /etc/dnsmasq.priv/toggle/focus.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.priv/toggle/focus.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     exit
