Create new services: Metis

diff --git a/raspberrypi/bin/unlock b/raspberrypi/bin/unlock
--- a/raspberrypi/bin/unlock
+++ b/raspberrypi/bin/unlock
@@ -112,6 +112,9 @@ main() {
         "athena")
           athena
           ;;
+        "metis")
+          metis
+          ;;
         "minerva")
           minerva
           ;;
@@ -295,6 +298,10 @@ all() {
 
   if ! [ -L /etc/dnsmasq.toggle/athena_allow.conf ]; then
     sudo ln -s /home/ubuntu/workspace/dnsmasq-conf/dnsmasq/dnsmasq.toggle/athena_allow.conf /etc/dnsmasq.toggle
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/metis.conf ]; then
+    sudo unlink /etc/dnsmasq.toggle/metis.conf
   fi
 
   if [ -L /etc/dnsmasq.toggle/minerva.conf ]; then
@@ -528,6 +535,14 @@ all() {
   if ! [ -L /etc/dnsmasq.toggle/athena_allow.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/athena_allow.conf still doesn't exist" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+    not_all_linkage_succeeded=1
+  fi
+
+  if [ -L /etc/dnsmasq.toggle/metis.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/metis.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
     not_all_linkage_succeeded=1
@@ -1242,6 +1257,26 @@ athena() {
   if [ -L /etc/dnsmasq.toggle/athena.conf ]; then
     error_color
     echo "error: /etc/dnsmasq.toggle/athena.conf still exists" >&2
+    no_color
+    echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
+  else
+    linkage_succeeded=1
+  fi
+}
+
+metis() {
+  reference_minute=60
+  [ "$DRY_RUN" = 1 ] && exit 0
+
+  warning_color
+  sudo unlink /etc/dnsmasq.toggle/metis.conf
+  no_color
+
+  pause "$waiting_interval" "$WAITING_MESSAGE"
+
+  if [ -L /etc/dnsmasq.toggle/metis.conf ]; then
+    error_color
+    echo "error: /etc/dnsmasq.toggle/metis.conf still exists" >&2
     no_color
     echo "info: dnsmasq.service: $(sudo systemctl is-active dnsmasq)"
   else
